name: FastAPI CI/CD

on:
  # Trigger the workflow on push
  push:
    branches: 
      # Push events on main branch
      - master 

# The Job defines a series of steps that execute on the same runner.
jobs:

  CI:
    # Define the runner used in the workflow
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run test -v

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main
        
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
          
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: fastapilaisar2.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      
      - name: Build and push container image to registry 
        run: |
          docker build . -t fastapilaisar.azurecr.io/fastapi-cd:${{ github.sha }}
          docker push fastapilaisar.azurecr.io/fastapi-cd:${{ github.sha }}
          
          
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fastapilaisar'
          images: 'fastapilaisar.azurecr.io/fastapi-cd:${{ github.sha }}'
          slot-name: 'production'
          
          
      - name: Azure logout
        run: |
          az logout